#ifndef PAPER_SHADER_CONSTANTS_H
#define PAPER_SHADER_CONSTANTS_H
// Shared CPU/HLSL/MSL ABI capacity and deterministic noise specification.
#define PAPER_MAX_SCENE_LIGHTS 16
#define PAPER_SMOKE_FACE_COUNT 20
#define PAPER_MINIMUM_SQUARED_DIRECTION 0.0000000001
#define PAPER_NOISE_HASH_X 374761393u
#define PAPER_NOISE_HASH_Y 668265263u
#define PAPER_NOISE_HASH_MIX 1274126177u
#define PAPER_NOISE_HASH_SHIFT 13
#define PAPER_NOISE_GRAIN_LEVELS 17u
#define PAPER_NOISE_GRAIN_HALF_RANGE 8
#define PAPER_NOISE_BAND_PERIOD 211u
#define PAPER_NOISE_BAND_WIDTH 2u
#define PAPER_NOISE_BAND_Y 73u
#define PAPER_NOISE_BAND_TICK 31u
#endif
